# Utilisation d'une image officielle de Java pour Spring Boot
FROM openjdk:17-jdk-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier JAR généré par Maven dans le conteneur
COPY ./Backend-Spring/target/bankdash-app.jar /app/bankdash-app.jar

# Exposer le port 8080 pour Spring Boot
EXPOSE 8080

# Commande pour exécuter l'application Spring Boot
ENTRYPOINT ["java", "-jar", "/app/bankdash-app.jar"]
